version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shadowhand